language: node_js
node_js:
  - "8"

install:
  - npm install
  - npm install -g gulp-cli

script:
  - gulp build

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_CI_TOKEN
  on:
    branch: master
